spring:
  application:
    name: zuul

server:
  port: 8768

eureka:
  client:
    service-url:
      default-zone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/
#      default-zone: http://localhost:8761/eureka/

zuul:
  routes:
    pc:
      serviceId: service-feign
      path: /pc/**
    phone:
      serviceId: service-ribbon
      path: /phone/**