
spring.application.name: config-server
server.port: 8769

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liuyunpeng788/swagger-demo
          search-paths: src/main/resources
          default-label: master
          username: liuyunpeng788
          password: lyp5257918
          refresh-rate: 10

